version: '3'
services:
  service1:
    build:
      context: ./service1
    ports:
      - "8081:8081"
  service2:
    build:
      context: ./service2
    ports:
      - "8082:8082"
  teams:
    build:
      context: ./teams
    ports:
      - "8083:8083"
  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
