version: '3'
services:
  service1:
    build:
      context: ./service1
    container_name : service1
    environment:
      - MONGO_URI = mongodb+srv://ilhansyed:devrevler@cluster0.daiu1xh.mongodb.net/?retryWrites=true&w=majority
      - BACKENDSERVICE1PORT = 8081
  service2:
    build:
      context: ./service2
    container_name : service2
    environment:
      - MONGO_URI = mongodb+srv://ilhansyed:devrevler@cluster0.daiu1xh.mongodb.net/?retryWrites=true&w=majority
      - BACKENDSERVICE2PORT = 8082
  teams:
    build:
      context: ./teams
    container_name : teams
    environment:
      - MONGO_URI = mongodb+srv://ilhansyed:devrevler@cluster0.daiu1xh.mongodb.net/?retryWrites=true&w=majority
      - BACKENDSERVICE3PORT = 8083
  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI = mongodb+srv://ilhansyed:devrevler@cluster0.daiu1xh.mongodb.net/?retryWrites=true&w=majority
      - GATEWAYPORT = 8080
      - BACKENDSERVICE1PORT = 8081
      - BACKENDSERVICE2PORT = 8082
      - BACKENDSERVICE3PORT = 8083
      - BACKENDSERVICE1URL = service1
      - BACKENDSERVICE2URL = service2
      - BACKENDSERVICE3URL = teams
