name: service-ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_all:
    name: Simulate Build & push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

  build_service1:
    name: Simulate Build & push Docker image for service1
    runs-on: ubuntu-latest

    steps:
      - name: Simulating building service1 Docker image
        run: echo "Simulating building and pushing service1 Docker image."

  build_service2:
    name: Simulate Build & push Docker image for service2
    runs-on: ubuntu-latest

    steps:
      - name: Simulating building service2 Docker image
        run: echo "Simulating building and pushing service2 Docker image."

  build_teams:
    name: Simulate Build & push Docker image for teams
    runs-on: ubuntu-latest

    steps:
      - name: Simulating building teams Docker image
        run: echo "Simulating building and pushing teams Docker image."

  build_gateway:

    name: Simulate Build & push Docker image for gateway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code for gateway
        uses: actions/checkout@v2
        with:
          repository: 'github.com/syshil/gateway'
          ref: main
          path: gateway

      - name: Get commit-hash for gateway
        id: get_gateway_commit_hash
        run: echo "commit-hash-gateway=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check if commit hash matches
        if: github.sha == steps.get_gateway_commit_hash.outputs.commit-hash-gateway
        run: echo "Simulating building and pushing gateway Docker image."
