name: service-ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_all:
    name: Simulate Build & push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get commit-hash for service1
        id: get_service1_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build_service1:
    name: Simulate Build & push Docker image for service1
    needs: build_all
    runs-on: ubuntu-latest

    steps:
      - name: Simulating building service1 Docker image
        run: echo "Simulating building and pushing service1 Docker image."

  build_service2:
    name: Simulate Build & push Docker image for service2
    needs: build_service1
    runs-on: ubuntu-latest

    steps:
      - name: Simulating building service2 Docker image
        run: echo "Simulating building and pushing service2 Docker image."

  build_teams:
    name: Simulate Build & push Docker image for teams
    needs: build_service2
    runs-on: ubuntu-latest

    steps:
      - name: Simulating building teams Docker image
        run: echo "Simulating building and pushing teams Docker image."

  build_gateway:
    name: Simulate Build & push Docker image for gateway
    needs: build_teams
    runs-on: ubuntu-latest

    steps:
      - name: Get commit-hash for gateway
        id: get_gateway_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check if commit hash matches
        if: steps.get_service1_commit_hash.outputs.commit-hash == steps.get_gateway_commit_hash.outputs.commit-hash
        run: echo "Simulating building and pushing gateway Docker image."
        
