name: service1-ci

on:
  push:
    branches: 
      - main
      
permissions:
  contents: write

jobs:

  build:
    name: Build & push docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: getting commit-hash
      id: get_commit_hash
      run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build User Image
      uses: docker/build-push-action@v2
      with:
        context: ./service1
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cricket:${{steps.get_commit_hash.outputs.commit-hash}}

      #   run: pwd && sudo add-apt-repository ppa:rmescandon/yq && sudo apt-get install -y yq && yq e -i ".spec[0].template.spec.containers[0].image = \"${{ secrets.DOCKER_USERNAME }}/capstone_user:${{steps.get_commit_hash.outputs.commit-hash}}\"" ./deployment/kube/users.yaml
      # - name: configure git
      #   run: |
      #     git config --global user.name ${{ secrets.USERNAME }}
      #     git config --global user.email ${{ secrets.EMAIL }}
      #     git config pull.rebase true
      #     git checkout main
      #     git add .
      #     git commit -m "Automated depl"
      #     git pull origin main

     
