name: service-ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_all:
    name: Build & push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get commit-hash for service1
        id: get_service1_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build_service1:
    name: Build & push Docker image for service1
    needs: build_all
    runs-on: ubuntu-latest

    steps:
      - name: Simulate building and pushing service1 Docker image
        run: echo "Service1 Docker image build simulation"

  build_service2:
    name: Build & push Docker image for service2
    needs: build_service1
    runs-on: ubuntu-latest

    steps:
      - name: Get commit-hash for service2
        id: get_service2_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Simulate building and pushing service2 Docker image
        run: echo "Service2 Docker image build simulation"

  build_teams:
    name: Build & push Docker image for teams
    needs: build_service2
    runs-on: ubuntu-latest

    steps:
      - name: Get commit-hash for teams
        id: get_teams_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Simulate building and pushing teams Docker image
        run: echo "Teams Docker image build simulation"

  build_gateway:
    name: Build & push Docker image for gateway
    needs: build_teams
    runs-on: ubuntu-latest

    steps:
      - name: Get commit-hash for gateway
        id: get_gateway_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Simulate building and pushing gateway Docker image
        run: echo "Gateway Docker image build simulation"
