name: service-ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_all:
    name: Build & push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get commit-hash for service1
        id: get_service1_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build_service1:
    name: Build & push Docker image for service1
    needs: build_all
    runs-on: ubuntu-latest

    steps:
      - name: Build and push service1 Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./service1
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cricket/service1:${{ steps.get_service1_commit_hash.outputs.commit-hash }}

  build_service2:
    name: Build & push Docker image for service2
    needs: build_service1
    runs-on: ubuntu-latest

    steps:
      - name: Get commit-hash for service2
        id: get_service2_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push service2 Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./service2
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cricket/service2:${{ steps.get_service2_commit_hash.outputs.commit-hash }}

  build_teams:
    name: Build & push Docker image for teams
    needs: build_service2
    runs-on: ubuntu-latest

    steps:
      - name: Get commit-hash for teams
        id: get_teams_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push teams Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./teams
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cricket/teams:${{ steps.get_teams_commit_hash.outputs.commit-hash }}

  build_gateway:
    name: Build & push Docker image for gateway
    needs: build_teams
    runs-on: ubuntu-latest

    steps:
      - name: Get commit-hash for gateway
        id: get_gateway_commit_hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Check if commit hash matches
        run: |
          if [[ "${{ steps.get_gateway_commit_hash.outputs.commit-hash }}" == "$(git rev-parse --short HEAD)" ]]; then
            echo "Building and pushing gateway Docker image."
            docker/build-push-action@v2
          else
            echo "Commit hash does not match, skipping gateway build."
          fi
        if: steps.get_gateway_commit_hash.outputs.commit-hash != ''
